-- MySQL Script generated by MySQL Workbench
-- Wed Oct  7 00:59:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema phonebook
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `phonebook` ;

-- -----------------------------------------------------
-- Schema phonebook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `phonebook` DEFAULT CHARACTER SET utf8 ;
USE `phonebook` ;

-- -----------------------------------------------------
-- Table `phonebook`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phonebook`.`persons` (
  `person_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `phonebook`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phonebook`.`contacts` (
  `contact_id` BIGINT NOT NULL AUTO_INCREMENT,
  `telephone` VARCHAR(255) NULL DEFAULT NULL,
  `person_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`contact_id`),
  INDEX `FK6ymgxge265x1ybkojs9ybgov9` (`person_id` ASC) VISIBLE,
  CONSTRAINT `FK6ymgxge265x1ybkojs9ybgov9`
    FOREIGN KEY (`person_id`)
    REFERENCES `phonebook`.`persons` (`person_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
